global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["localhost:5001"]

  - job_name: "order-service"
    static_configs:
      - targets: ["localhost:5002"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["localhost:5003"]
